const DYNAMO_ENTITIES_PREFIX = {
  RESERVATIONS: "RESERVATIONS#",
  CUSTOMERS: "CUSTOMERS#",
  HOTELS: "HOTELS#",
};

const HOTELS = {
  ENRICO_HOTEL: "3df5ec8c-1535-4bab-ab03-8b6c621c6237",
};

export { DYNAMO_ENTITIES_PREFIX, HOTELS };
